#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-glanceclient
Version  : 2.0.0
Release  : 25
URL      : http://tarballs.openstack.org/python-glanceclient/python-glanceclient-2.0.0.tar.gz
Source0  : http://tarballs.openstack.org/python-glanceclient/python-glanceclient-2.0.0.tar.gz
Summary  : OpenStack Image API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-glanceclient-bin
Requires: python-glanceclient-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : fixtures-python
BuildRequires : jsonpatch-python
BuildRequires : jsonpointer-python
BuildRequires : jsonschema-python
BuildRequires : msgpack-python-python
BuildRequires : oslo.i18n-python
BuildRequires : oslo.utils-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-keystoneclient-python
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : tempest-lib-python
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : warlock-python

%description
Python bindings to the OpenStack Images API
===========================================

%package bin
Summary: bin components for the python-glanceclient package.
Group: Binaries

%description bin
bin components for the python-glanceclient package.


%package python
Summary: python components for the python-glanceclient package.
Group: Default
Requires: oslo.i18n-python
Requires: oslo.utils-python
Requires: python-keystoneclient-python
Requires: requests-python
Requires: warlock-python

%description python
python components for the python-glanceclient package.


%prep
%setup -q -n python-glanceclient-2.0.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glance

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
