#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-glanceclient
Version  : 3.2.0
Release  : 63
URL      : https://files.pythonhosted.org/packages/b8/d8/0cb5fcb181a057256dbdc07c903d0ee914dac18726f13a5b4430b538a0a6/python-glanceclient-3.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b8/d8/0cb5fcb181a057256dbdc07c903d0ee914dac18726f13a5b4430b538a0a6/python-glanceclient-3.2.0.tar.gz
Summary  : OpenStack Image API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-glanceclient-bin = %{version}-%{release}
Requires: python-glanceclient-license = %{version}-%{release}
Requires: python-glanceclient-python = %{version}-%{release}
Requires: python-glanceclient-python3 = %{version}-%{release}
Requires: keystoneauth1
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: pyOpenSSL
Requires: requests
Requires: six
Requires: warlock
Requires: wrapt
BuildRequires : buildreq-distutils3
BuildRequires : keystoneauth1
BuildRequires : oslo.i18n
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : pyOpenSSL
BuildRequires : requests
BuildRequires : six
BuildRequires : warlock
BuildRequires : wrapt

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the python-glanceclient package.
Group: Binaries
Requires: python-glanceclient-license = %{version}-%{release}

%description bin
bin components for the python-glanceclient package.


%package license
Summary: license components for the python-glanceclient package.
Group: Default

%description license
license components for the python-glanceclient package.


%package python
Summary: python components for the python-glanceclient package.
Group: Default
Requires: python-glanceclient-python3 = %{version}-%{release}

%description python
python components for the python-glanceclient package.


%package python3
Summary: python3 components for the python-glanceclient package.
Group: Default
Requires: python3-core
Provides: pypi(python_glanceclient)
Requires: pypi(keystoneauth1)
Requires: pypi(oslo.i18n)
Requires: pypi(oslo.utils)
Requires: pypi(pbr)
Requires: pypi(prettytable)
Requires: pypi(pyopenssl)
Requires: pypi(requests)
Requires: pypi(six)
Requires: pypi(warlock)
Requires: pypi(wrapt)

%description python3
python3 components for the python-glanceclient package.


%prep
%setup -q -n python-glanceclient-3.2.0
cd %{_builddir}/python-glanceclient-3.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592611364
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-glanceclient
cp %{_builddir}/python-glanceclient-3.2.0/LICENSE %{buildroot}/usr/share/package-licenses/python-glanceclient/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glance

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-glanceclient/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
